CREATE TABLE events (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`EventID` INT(10) NOT NULL,
`EventName` VARCHAR(255) NOT NULL,
`EventCategory` VARCHAR(255) NOT NULL,
`StartTime` TIMESTAMP NOT NULL,
`EndTime` TIMESTAMP NOT NULL,
UNIQUE (`Start Time`, `Event ID`)
);
